export const SERVICE_CATALOG = {
  HOME_CLEANING: { name:'Home Cleaning', category:'Personal', startingPrice:999, unit:'per visit', includes:['Dusting and wiping accessible surfaces','Floor sweeping and mopping','Kitchen exterior cleaning','Bathroom cleaning and sanitisation','General waste collection'], excludes:['Heavy stain removal','Pest control','Exterior facade work','Moving heavy furniture'], terms:['Minimum service booking applies','Customer should provide reasonable access to the premises','Final scope may change for unusually heavy dirt or additional areas','Cancellation/rescheduling should be made before the scheduled slot','Prices are exclusive of GST where applicable'] },
  DEEP_CLEANING: { name:'Deep Cleaning', category:'Personal', startingPrice:1499, unit:'per service', includes:['Detailed dusting of accessible surfaces','Kitchen deep-clean of standard accessible areas','Bathroom deep-clean','Floor cleaning','Cobweb removal','General sanitisation'], excludes:['Pest control','Permanent stain restoration','High-risk biohazard cleaning','Exterior facade cleaning'], terms:['Price is a starting estimate and may vary by scope','Specialist chemicals or equipment may attract additional charges','Customer must disclose hazardous materials or restricted areas','Cancellation and rescheduling are subject to availability'] },
  SOFA_CARPET: { name:'Sofa & Carpet Cleaning', category:'Personal', startingPrice:799, unit:'per service', includes:['Vacuuming','Spot treatment for normal stains','Machine cleaning where suitable','Basic deodorisation'], excludes:['Permanent dye damage','Severe mould remediation','Repair or restoration'], terms:['Material suitability is assessed before treatment','Colour bleeding or pre-existing damage is not covered','Drying time depends on ventilation and material'] },
  OFFICE_CLEANING: { name:'Office Cleaning', category:'Business', pricing:'employee_based', includes:['Routine floor care','Desk and common-area cleaning','Washroom cleaning','Kitchen/pantry cleaning','Waste handling','Consumables coordination as agreed','Supervisor/quality checks according to plan'], excludes:['Specialist facade access','Pest control','Major construction debris','Hazardous waste unless separately contracted'], terms:['Recurring price is based on people served and selected service plan','Service frequency and working hours are agreed in the service plan','Customer provides access, utilities and a safe working environment','Extra areas or materially changed occupancy may require repricing','Annual plans are billed according to the selected commercial agreement','GST and statutory charges apply where required','Service is subject to site safety and access requirements'] },
  SCHOOL_CLEANING: { name:'School Cleaning', category:'Business', pricing:'employee_based', includes:['Classroom cleaning','Corridor and common-area cleaning','Washroom hygiene','Staff-room cleaning','Waste collection','High-touch surface sanitisation','Routine quality inspections'], excludes:['Medical waste treatment','Pest control','Major repairs','Specialist hazardous-material remediation'], terms:['Pricing is based on people served and agreed operating schedule','School must identify restricted/sensitive areas','Cleaning schedules must respect school operating hours and safety requirements','Consumables included only where specified in the selected plan','Additional events or extraordinary cleaning are chargeable separately','GST applies where required'] },
  HOSPITAL_CLEANING: { name:'Hospital Cleaning', category:'Business', pricing:'employee_based', includes:['Routine clinical-area cleaning','Non-clinical area cleaning','Washroom hygiene','High-touch disinfection','Waste segregation support according to agreed scope','Cleaning logs and quality checks'], excludes:['Clinical waste disposal unless separately contracted','Sterilisation of medical instruments','Pest control','Specialist hazardous remediation unless contracted'], terms:['Hospital must disclose infection-control requirements and restricted zones','Cleaning follows the agreed hospital SOP and access protocol','Specialist chemicals/PPE may be included only when stated in the plan','Biomedical and hazardous waste handling requires a separately defined scope','Service depends on safe access and authorised site personnel','Pricing is subject to scope, occupancy and required service frequency','GST applies where required'] },
  HOTEL_CLEANING: { name:'Hotel Cleaning', category:'Business', pricing:'employee_based', includes:['Guest-room routine cleaning','Common-area cleaning','Washroom hygiene','Lobby and corridor cleaning','Waste handling','Quality checks'], excludes:['Laundry unless contracted','Pest control','Major restoration','Specialist facade work'], terms:['Room count, occupancy and operating hours must be agreed','Turnaround requirements may affect staffing and price','Guest belongings remain the customer responsibility','Extra event cleaning is separately chargeable','GST applies where required'] },
  FACTORY_CLEANING: { name:'Factory Cleaning', category:'Business', pricing:'employee_based', includes:['Production-area housekeeping','Floor cleaning','Common-area cleaning','Washroom hygiene','Waste collection within agreed scope','Routine safety/quality checks'], excludes:['Chemical spill response','Hazardous waste disposal','Machine maintenance','Confined-space work unless separately approved'], terms:['Customer must disclose machinery, chemicals and hazardous zones','Only trained/authorised personnel may enter restricted areas','PPE and specialist equipment are included only when specified','Work may be scheduled around production operations','Hazardous materials require separate assessment and pricing'] },
  WAREHOUSE_CLEANING: { name:'Warehouse Cleaning', category:'Business', pricing:'employee_based', includes:['Floor sweeping/mopping','Dust removal','Common-area cleaning','Washroom hygiene','Waste collection','Routine inspection'], excludes:['High-level rack cleaning unless specified','Forklift operation','Hazardous spill response','Pest control'], terms:['Aisle access must be safe and unobstructed','High-level work requires separate assessment','Customer is responsible for identifying active loading zones','Service timing may be adjusted around warehouse operations'] },
  RETAIL_CLEANING: { name:'Retail Cleaning', category:'Business', pricing:'employee_based', includes:['Sales-floor cleaning','Entrance cleaning','Display-area dusting','Washroom cleaning','Waste handling','High-touch sanitisation'], excludes:['Product merchandising','Pest control','Exterior facade work','Specialist restoration'], terms:['Cleaning must be coordinated with store operating hours','Customer should secure valuables and sensitive merchandise','After-hours access requirements must be agreed','Extra promotional/event cleaning may be separately charged'] },
  GLASS_CLEANING: { name:'Glass & Window Cleaning', category:'All', startingPrice:999, unit:'per service', includes:['Internal glass cleaning','Accessible external glass cleaning','Frame wiping where accessible','Basic spot removal'], excludes:['Rope access','Crane/lift hire','Permanent mineral damage restoration','Unsafe/high-risk access'], terms:['High-rise or inaccessible glass requires separate assessment','Customer must provide safe access where applicable','Weather may require rescheduling of external work','Specialist access equipment is separately chargeable'] },
  FLOOR_CARPET_CARE: { name:'Floor & Carpet Care', category:'All', startingPrice:1299, unit:'per service', includes:['Vacuuming','Machine cleaning where suitable','Basic spot treatment','Mopping/standard floor care'], excludes:['Floor replacement','Permanent damage restoration','Specialist stone restoration unless quoted'], terms:['Material is assessed for suitable treatment','Existing damage remains customer responsibility','Drying time depends on material and ventilation','Furniture movement is included only if specifically agreed'] },
  SANITISATION: { name:'Sanitisation & Hygiene', category:'All', startingPrice:1499, unit:'per service', includes:['High-touch surface disinfection','Washroom hygiene','Common-area sanitisation','Approved cleaning/disinfection process','Service completion record'], excludes:['Medical sterilisation','Biohazard remediation','Pest control'], terms:['Customer must disclose infectious-risk or hazardous conditions','Service is cleaning/disinfection, not medical sterilisation','Required PPE/specialist response may be separately quoted','Premises should remain accessible during the agreed service window'] },
  POST_CONSTRUCTION: { name:'Post-Construction Cleaning', category:'Business', pricing:'employee_based', includes:['Construction dust removal','Floor cleaning','Surface cleaning','Window/glass cleaning where accessible','Debris collection within agreed scope','Final presentation clean'], excludes:['Heavy debris disposal','Hazardous material removal','Paint stripping beyond agreed scope','Structural repairs'], terms:['Site must be safe and released for cleaning','Construction contractors must remove hazardous materials before service','Heavy debris, specialist equipment and disposal are quoted separately','Final price depends on site condition and scope'] },
  MOVE_IN_OUT: { name:'Move-in / Move-out Cleaning', category:'All', startingPrice:1799, unit:'per service', includes:['Floor cleaning','Kitchen cleaning','Bathroom cleaning','Dusting','Accessible surface cleaning','General waste collection'], excludes:['Furniture removal','Pest control','Permanent stain restoration','Repairs'], terms:['Property must be accessible at the booked time','Utilities should be available where needed','Heavy dirt or additional rooms may change the final quote','Customer must remove valuables and personal belongings'] }
};

export const SERVICE_TERMS = [
 'Displayed prices are estimates/starting prices unless explicitly marked fixed.',
 'GST and legally applicable taxes are additional unless the displayed price explicitly includes them.',
 'The customer is responsible for providing accurate premises, occupancy, access and service information.',
 'CleanOps may recommend a revised scope or price where actual site conditions materially differ from the booking information.',
 'Cleaning personnel must be provided a safe working environment and reasonable access to the agreed areas.',
 'Hazardous, biomedical, chemical, infectious, pest-control or specialist work is excluded unless expressly included in a signed service scope.',
 'Damage caused by pre-existing defects, unsuitable materials, concealed conditions or customer-supplied chemicals is not covered as routine service liability.',
 'Recurring services operate according to the agreed frequency, staffing, working hours and service-level plan.',
 'Customers may request rescheduling/cancellation subject to the applicable booking or contract terms and workforce availability.',
 'Annual plans are subject to the agreed minimum term and payment schedule shown before confirmation.',
 'Service completion, quality checks, complaints and rework are managed through the CleanOps service workflow.',
 'The final commercial agreement/contract prevails over general catalogue wording where the two differ.'
];
