'use client';
import { useEffect, useState } from 'react';

const box={border:'1px solid #e2e8f0',borderRadius:14,padding:18,background:'#fff',marginBottom:14};
const field={display:'block',width:'100%',boxSizing:'border-box',padding:12,border:'1px solid #cbd5e1',borderRadius:9,marginTop:6};
export default function ComplaintsPage(){
 const [items,setItems]=useState([]),[facilities,setFacilities]=useState([]),[description,setDescription]=useState(''),[facilityId,setFacilityId]=useState(''),[severity,setSeverity]=useState('MEDIUM'),[message,setMessage]=useState(''),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false);
 async function load(){setLoading(true);try{const [a,b]=await Promise.all([fetch('/api/complaints',{cache:'no-store'}),fetch('/api/facilities',{cache:'no-store'})]);const x=await a.json(),y=await b.json();if(!a.ok)throw new Error(x.error||'Unable to load complaints');setItems(x.data||[]);setFacilities(y.data||[])}catch(e){setMessage(e.message)}finally{setLoading(false)}}
 useEffect(()=>{load()},[]);
 async function submit(e){e.preventDefault();setSaving(true);setMessage('');try{const r=await fetch('/api/complaints',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({description,facilityId:facilityId||undefined,severity})});const x=await r.json();if(!r.ok)throw new Error(x.error||'Unable to submit complaint');setDescription('');setFacilityId('');setSeverity('MEDIUM');setMessage('Complaint submitted. Your operations team can now review it.');await load()}catch(e){setMessage(e.message)}finally{setSaving(false)}}
 return <main style={{fontFamily:'Inter,system-ui',maxWidth:900,margin:'auto',padding:24,color:'#102a2a',background:'#f8faf9',minHeight:'100vh'}}><a href="/client" style={{color:'#0d6b61'}}>← Client portal</a><header style={{margin:'22px 0'}}><h1 style={{fontSize:32,margin:'0 0 6px'}}>Service support</h1><p style={{color:'#64748b'}}>Report a service issue and track the resolution in one place.</p></header>{message&&<p role="status" style={{padding:12,borderRadius:9,background:'#ecfdf5',color:'#166534'}}>{message}</p>}
 <form onSubmit={submit} style={box}><h2 style={{marginTop:0}}>Raise a complaint</h2><label>Facility<select style={field} value={facilityId} onChange={e=>setFacilityId(e.target.value)}><option value="">General / not site-specific</option>{facilities.map(f=><option key={f.id} value={f.id}>{f.name}</option>)}</select></label><label style={{display:'block',marginTop:12}}>Severity<select style={field} value={severity} onChange={e=>setSeverity(e.target.value)}>{['LOW','MEDIUM','HIGH','CRITICAL'].map(s=><option key={s}>{s}</option>)}</select></label><label style={{display:'block',marginTop:12}}>Describe the issue<textarea required minLength={5} maxLength={4000} style={{...field,minHeight:110}} value={description} onChange={e=>setDescription(e.target.value)} placeholder="Tell us what happened, where, and what needs to be fixed."/></label><button disabled={saving} style={{marginTop:14,padding:'12px 18px',border:0,borderRadius:9,background:'#0d6b61',color:'#fff',fontWeight:800}}>{saving?'Submitting…':'Submit complaint'}</button></form>
 <section><h2 style={{marginBottom:12}}>Your complaints</h2>{loading?<p>Loading…</p>:items.length?items.map(x=><article key={x.id} style={box}><div style={{display:'flex',justifyContent:'space-between',gap:12,flexWrap:'wrap'}}><b>{x.facility?.name||'General service issue'}</b><span style={{padding:'4px 9px',borderRadius:999,background:'#eef2f7',fontSize:12}}>{x.status.replaceAll('_',' ')}</span></div><p>{x.description}</p><small style={{color:'#64748b'}}>Severity: {x.severity} · Submitted {new Date(x.createdAt).toLocaleString('en-IN')}</small>{x.resolution&&<p><b>Resolution:</b> {x.resolution}</p>}</article>):<p style={{color:'#64748b'}}>No complaints have been submitted yet.</p>}</section>
 </main>;
}
