'use client';
import {useState} from 'react';

export default function CustomerLogin(){
 const [mode,setMode]=useState('signin'),[name,setName]=useState(''),[phone,setPhone]=useState(''),[password,setPassword]=useState(''),[msg,setMsg]=useState(''),[busy,setBusy]=useState(false);
 async function submit(e){e.preventDefault();setBusy(true);setMsg('');try{const endpoint=mode==='signup'?'/api/customer/register':'/api/auth/login';const body=mode==='signup'?{name,phone,password}:{phone,password};const r=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw new Error(d.error||'Unable to continue');window.location.href='/client';}catch(e){setMsg(e.message||'Unable to continue')}finally{setBusy(false)}}
 return <main style={shell}><section style={card}><a href="/" style={back}>← CleanOps</a><div style={eyebrow}>CUSTOMER APP</div><h1 style={title}>{mode==='signin'?'Welcome back':'Create your account'}</h1><p style={muted}>{mode==='signin'?'Use your mobile number to continue booking.':'Create your CleanOps account and start booking services.'}</p><div style={tabs}><button type="button" onClick={()=>{setMode('signin');setMsg('')}} style={mode==='signin'?tabOn:tab}>Sign in</button><button type="button" onClick={()=>{setMode('signup');setMsg('')}} style={mode==='signup'?tabOn:tab}>Create account</button></div><form onSubmit={submit}>{mode==='signup'&&<label style={label}>Name<input required value={name} onChange={e=>setName(e.target.value)} placeholder="Your name" style={input}/></label>}<label style={{...label,marginTop:14}}>Mobile number<input required inputMode="tel" autoComplete="tel" placeholder="+91 98XXXXXXXX" value={phone} onChange={e=>setPhone(e.target.value)} style={input}/></label><label style={{...label,marginTop:14}}>Password<input required minLength={6} type="password" autoComplete={mode==='signin'?'current-password':'new-password'} placeholder="At least 6 characters" value={password} onChange={e=>setPassword(e.target.value)} style={input}/></label><button disabled={busy} style={button}>{busy?'Please wait…':mode==='signin'?'Continue':'Create account'}</button>{msg&&<p style={error}>{msg}</p>}</form><div style={trust}><span>✓</span> Mobile-first customer account · Secure session</div></section></main>}
const shell={minHeight:'100vh',display:'grid',placeItems:'center',padding:24,boxSizing:'border-box',fontFamily:'Inter,system-ui,sans-serif',background:'#eef2ef',color:'#14211d'};
const card={width:'min(440px,100%)',boxSizing:'border-box',background:'#fff',border:'1px solid #dfe7e3',borderRadius:22,padding:28,boxShadow:'0 20px 70px rgba(20,40,32,.10)'};
const back={textDecoration:'none',color:'#31534a',fontSize:13,fontWeight:800};const eyebrow={marginTop:36,fontSize:10,letterSpacing:1.5,fontWeight:900,color:'#078b48'};const title={fontSize:34,letterSpacing:'-.04em',margin:'6px 0 7px'};const muted={color:'#718079',lineHeight:1.5,fontSize:12};const tabs={display:'grid',gridTemplateColumns:'1fr 1fr',gap:3,background:'#f0f2f1',padding:3,borderRadius:10,margin:'20px 0'};const tab={border:0,background:'transparent',borderRadius:8,padding:10,fontWeight:800,color:'#40514b'};const tabOn={...tab,background:'#079447',color:'#fff'};const label={display:'block',fontSize:12,fontWeight:800};const input={display:'block',width:'100%',boxSizing:'border-box',padding:13,marginTop:7,border:'1px solid #cad9d5',borderRadius:11,fontSize:14,outline:'none',background:'#fff'};const button={width:'100%',padding:14,marginTop:18,border:0,borderRadius:11,background:'#079447',color:'#fff',fontWeight:900,fontSize:14};const error={color:'#b42318',fontSize:12};const trust={marginTop:18,padding:'11px 12px',background:'#eef8f2',borderRadius:10,color:'#3e625c',fontSize:11};