'use client';
import {useState} from 'react';

export default function CustomerLogin(){
 const [phone,setPhone]=useState(''); const [password,setPassword]=useState(''); const [msg,setMsg]=useState(''); const [busy,setBusy]=useState(false);
 async function submit(e){e.preventDefault();setBusy(true);setMsg('Signing you in…');try{const r=await fetch('/api/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({phone,password})});const d=await r.json();if(r.ok)location.href='/client';else setMsg(d.error||'Unable to sign in');}catch{setMsg('Unable to connect. Please try again.')}finally{setBusy(false)}}
 return <main style={shell}><section style={card}><a href="/" style={back}>← CleanOps Pro</a><div style={eyebrow}>CUSTOMER APP</div><h1 style={title}>Welcome back</h1><p style={muted}>Book, manage and track your cleaning services from one place.</p><form onSubmit={submit} style={{marginTop:26}}><label style={label}>Mobile number<input required inputMode="tel" autoComplete="tel" placeholder="+91 98XXXXXXXX" value={phone} onChange={e=>setPhone(e.target.value)} style={input}/></label><label style={{...label,marginTop:14}}>Password<input required type="password" autoComplete="current-password" placeholder="Your password" value={password} onChange={e=>setPassword(e.target.value)} style={input}/></label><button disabled={busy} style={button}>{busy?'Signing in…':'Continue'}</button>{msg&&<p style={error}>{msg}</p>}</form><p style={{...muted,textAlign:'center',marginTop:22}}>New to CleanOps? <a href="/register" style={link}>Create your account</a></p><div style={trust}><span>✓</span> Secure customer access · Mobile-first account</div></section></main>
}
const shell={minHeight:'100vh',display:'grid',placeItems:'center',padding:24,boxSizing:'border-box',fontFamily:'Inter,system-ui,sans-serif',background:'linear-gradient(145deg,#eef7f5 0%,#fbfcfc 48%,#eef3f2 100%)',color:'#102a2a'};
const card={width:'min(440px,100%)',boxSizing:'border-box',background:'rgba(255,255,255,.94)',border:'1px solid #dfe9e6',borderRadius:24,padding:30,boxShadow:'0 24px 80px rgba(16,42,42,.10)'};
const back={textDecoration:'none',color:'#41615d',fontSize:13,fontWeight:700}; const eyebrow={marginTop:45,fontSize:11,letterSpacing:1.6,fontWeight:900,color:'#0d6b61'}; const title={fontSize:42,letterSpacing:'-.04em',margin:'7px 0 10px'}; const muted={color:'#6b7d79',lineHeight:1.55}; const label={display:'block',fontSize:13,fontWeight:800}; const input={display:'block',width:'100%',boxSizing:'border-box',padding:'14px 13px',marginTop:7,border:'1px solid #cad9d5',borderRadius:12,fontSize:15,outline:'none',background:'#fff'}; const button={width:'100%',padding:14,marginTop:20,border:0,borderRadius:12,background:'#0d6b61',color:'#fff',fontWeight:900,fontSize:15,cursor:'pointer'}; const error={color:'#b42318',fontSize:13}; const link={color:'#0d6b61',fontWeight:800}; const trust={marginTop:20,padding:'11px 12px',background:'#f0f8f5',borderRadius:10,color:'#3e625c',fontSize:12};