'use client';
import { useEffect, useState } from 'react';

export default function ReworkPage() {
  const [items, setItems] = useState([]); const [msg, setMsg] = useState(''); const [busy, setBusy] = useState('');
  async function load(){ try { const r=await fetch('/api/rework',{cache:'no-store'}); const x=await r.json(); if(!r.ok) throw new Error(x.error||'Unable to load'); setItems(x.data||[]); } catch(e){setMsg(e.message);} }
  useEffect(()=>{load();},[]);
  async function complete(id){ setBusy(id); setMsg(''); try { const correctiveAction=window.prompt('Confirm corrective action completed:','Rework completed and ready for inspection'); if(!correctiveAction) return; const r=await fetch('/api/rework/complete',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({reworkId:id,correctiveAction})}); const x=await r.json(); if(!r.ok) throw new Error(x.error||'Unable to complete rework'); setMsg('Rework completed. Job returned to Inspection for QA.'); await load(); } catch(e){setMsg(e.message);} finally{setBusy('');} }
  return <main style={{fontFamily:'Inter,system-ui',padding:32,maxWidth:1150,margin:'auto'}}><a href="/">← Operations</a><header style={{display:'flex',justifyContent:'space-between',alignItems:'center',margin:'20px 0'}}><div><h1>Rework & Re-inspection</h1><p style={{color:'#64748b'}}>Close corrective work and automatically return the job to QA.</p></div><button onClick={load} style={{padding:'10px 14px',border:'1px solid #cbd5e1',background:'#fff',borderRadius:8}}>Refresh</button></header>{msg&&<div style={{padding:12,background:'#f8fafc',borderRadius:8,marginBottom:16}}>{msg}</div>}<section style={{display:'grid',gap:14}}>{items.length===0?<div style={{padding:24,border:'1px dashed #cbd5e1',borderRadius:14}}>No rework items in your queue.</div>:items.map(r=><article key={r.id} style={{border:'1px solid #e5eaee',borderRadius:14,padding:20}}><div style={{display:'flex',justifyContent:'space-between',gap:16}}><div><h3 style={{margin:'0 0 6px'}}>{r.job?.facility?.name||'Facility'}</h3><p style={{margin:0,color:'#64748b'}}>Job {r.jobId} · {r.reason}</p>{r.correctiveAction&&<p><strong>Action:</strong> {r.correctiveAction}</p>}{r.dueAt&&<small>Due {new Date(r.dueAt).toLocaleString('en-IN')}</small>}</div><div style={{textAlign:'right'}}><span style={{padding:'5px 9px',borderRadius:999,background:r.status==='COMPLETED'?'#dcfce7':'#fef3c7'}}>{r.status}</span>{r.status!=='COMPLETED'&&r.status!=='CANCELLED'&&<div style={{marginTop:14}}><button disabled={busy===r.id} onClick={()=>complete(r.id)} style={{padding:'10px 14px',border:0,borderRadius:8,background:'#0d6b61',color:'#fff'}}>{busy===r.id?'Saving…':'Complete & Send to QA'}</button></div>}</div></div></article>)}</section></main>
}
